---
layout: post
title: 2018-2-1 TIL JAVA Exception
---

## 예외처리

- 프로그램실행중 예기치 못한 사건을 예외라고 한다. 예외 상황을 미리 예측하고 처리할 수 있는데, 이렇게 하는 것을 예외 처리라고 한다.

![](/Users/jimmy/Desktop/exception.png)

```
 public class ExceptionExam {
        public static void main(String[] args) {
            int i = 10;
            int j = 5;
            int k = i / j;
            System.out.println(k);
            System.out.println(main 종료!!);
        }
    }
```

```
package Exception;

public class ExceptionExam {
    public static void main(String [] args){
        int i = 10;
        int j = 0;
        try {
            int k = i/j;
            System.out.println(k);
        } catch (ArithmeticException e){
            System.out.println("0으로 나눌 수 없습니다." + e.toString());
        } finally {
            System.out.println("오류가 발생했던 발생하지 않았던 무조건 실행");
        }
        System.out.println("main end");
    }
}

// result
0으로 나눌 수 없습니다.java.lang.ArithmeticException: / by zero
오류가 발생했던 발생하지 않았던 무조건 실행
main end
```

#### 예외처리 문법

- 오류가 발생할 예상 부분을 try라는 블록으로 감싼 후, 발생할 오류와 관련된 Exception을 catch라는 블록에서 처리한다.
- 오류가 발생했든 안했든 무조건 실행되는 finally라는 블록을 가질 수 있다.
- finally블록은 생략가능하다.


#### throws

- throws는 예외가 발생했을때 예외를 호출한 쪽에서 처리하도록 던져준다.

```
package Exception;

public class ExceptionExam2 {
    public static void main(String [] args){
        int i = 10;
        int j = 0;
        try {
            int k = divide(i, j); // 실제 오류를 처리해야되는 부분
            System.out.println(k);
        } catch (ArithmeticException e){
            System.out.println(e.toString());
        }

    }

    public static int divide(int i, int j) throws ArithmeticException {
        int k = i/j;
        return k;
    }
}

```

- divide 뒤에 throws ArithmeticException이 적혀있다. 이것은 divide메소드에서 ArithmeticException이 발생하니 divide메소드를 호출하는 쪽에서 오류를 처리하라는 의미이다.
